# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import miprepa.utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_enabled', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='courses/logo')),
                ('name', models.CharField(max_length=400)),
                ('count_questions', models.IntegerField(default=0)),
                ('identify', models.CharField(max_length=400, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/cover')),
                ('knowledge_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.KnowledgeArea')),
            ],
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('text', models.CharField(max_length=600)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='opciones')),
                ('date_show', models.CharField(blank=True, max_length=100)),
                ('year_show', models.IntegerField(default=0, verbose_name='Año de pregunta')),
                ('argument_answer', models.TextField(blank=True, verbose_name='Argumento de la respuesta')),
                ('bookmarked_by', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None)),
                ('verified', models.BooleanField(default=True)),
                ('source_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('is_enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=250)),
                ('frequency', models.IntegerField(default=0)),
                ('order_customize', models.IntegerField(default=0)),
                ('desc_order_customizer', models.CharField(blank=True, max_length=180)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.Course')),
            ],
            options={
                'verbose_name': 'Tema',
                'ordering': ['order_customize'],
                'verbose_name_plural': 'Temas',
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.Topic'),
        ),
    ]
