# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('courses', '0002_remove_course_knowledge_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='knowledge_area',
            field=models.ManyToManyField(related_name='courses', to='universities.KnowledgeArea'),
        ),
    ]
