# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import miprepa.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Texto')),
                ('is_resolved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='courses.Question', verbose_name='Pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
    ]
