# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import miprepa.utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del badge')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='badges/logo')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitar')),
                ('all_universities', models.BooleanField(default=False)),
                ('min_questions', models.IntegerField(blank=True, verbose_name='Cantidad mínima de preguntas de la universidad')),
                ('type', models.CharField(blank=True, choices=[('practice', 'Práctica'), ('survival', 'Sobreviviente'), ('miscellany', 'Miscelánea')], max_length=10)),
                ('min_quantity_challenge', models.IntegerField(blank=True, verbose_name='Cantidad mínima por Reto')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='universities.University')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Nivel')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='levels/logo')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitar')),
                ('min_experience', models.IntegerField(verbose_name='Experiencia mínima')),
                ('max_experience', models.IntegerField(verbose_name='Experiencia máxima')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserUniversityBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useruniversity_badges', to='badges.Badge')),
                ('user_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useruniversity_badges', to='accounts.UserUniversity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.AddField(
            model_name='badge',
            name='user_university',
            field=models.ManyToManyField(related_name='badges', through='badges.UserUniversityBadge', to='accounts.UserUniversity'),
        ),
    ]
