# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='min_questions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad mínima de preguntas de la universidad'),
        ),
    ]
