# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import miprepa.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_history', to='courses.Question')),
                ('user_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_history', to='accounts.UserUniversity')),
            ],
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
    ]
