# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_countquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countquestion',
            unique_together=set([('user_university', 'question')]),
        ),
    ]
