# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_history_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 6, 3)),
            preserve_default=False,
        ),
    ]
