# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import miprepa.utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/images/', verbose_name='Imagen')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('min_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad mínima')),
                ('max_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad máxima')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino'), ('b', 'Ambos')], max_length=1)),
                ('viewed', models.PositiveIntegerField(default=0, verbose_name='Numero de Recibidos')),
                ('knowldge_area', models.ManyToManyField(blank=True, related_name='notifications', to='universities.KnowledgeArea', verbose_name='Area')),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
                ('universities', models.ManyToManyField(blank=True, related_name='notifications', to='universities.University', verbose_name='Universidades')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Día y hora de lectura')),
                ('push_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to='notifications.Notification', verbose_name='Push notifications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            bases=(miprepa.utils.mixins.UidMixin, models.Model),
        ),
    ]
